### ISSUE TITLE
Implement a number of examples of how to filter/analyze the data and make them publicly available. 

### ISSUE THREAD

**Issue by samreid** [phetsims/together#24]
From #21 
> Implement a number of examples of how to filter/analyze the data and make them publicly available. 

I moved this to a separate issue so that we can thread a conversation about priority, scope, etc.

**Comment by samreid** [comment]
@ariel-phet or @kathy-phet can you comment about what is desired here before our August 31, 2015 deadline?

**Comment by samreid** [comment]
Here is a simple example I created in together/js/datamite.js, which creates a histogram of counts based on action type for the arch data stream:

```js
  // This is used for debugging purposes, to make
  // sure the messages are accurate.  This also serves as a sample of how to process the data.
  if ( phet.chipper.getQueryParameter( 'datamite.eventHistogram' ) ) {
    var messages = [];

    // When receive a stack of messages, format a string and output to console.
    var eventHistogramListener = function( message ) {
      messages.push( message );

      //make a histogram of events to help understand the data and see if events match up
      var events = {};

      // Recurse through children of a message
      var visit = function visit( message ) {
        var event = message.event;
        events[ event ] = events[ event ] || 0;
        events[ event ] = events[ event ] + 1;
        for ( var i = 0; message.children && i < message.children.length; i++ ) {
          visit( message.children[ i ] );
        }
      };
      for ( var i = 0; i < messages.length; i++ ) {
        visit( messages[ i ] );
      }
      console.log( JSON.stringify( events, null, '  ' ) );
    };
    arch.addArchListener( eventHistogramListener );
  }
```

**Comment by ariel-phet** [comment]
I believe our thought was always to have a couple of enlightening examples (perhaps 3 or so) that are well documented and show the idea of how you could filter or analyze data. The deeper idea being that if we "seed" with a couple of examples we might be able to encourage groups that use our software to contribute back filters they have come up with and have a community pool of such tools, but with us only having given the initial set and allowing things to grow organically to fit the community needs.

You will have to ask @kathy-phet in terms of goals for a particular deadline....since we are having continued funding under the same grant line, I am not sure if it is so critical to show this piece since we have made good progress in other areas, but only @kathy-phet can answer that question. With all we are doing, it strikes me as a lower priority.

**Comment by samreid** [comment]
#111 will be one simple example of filtering.  #77 is a simple (but useful!) example of processing.  Those seem sufficient at the moment, so I'll close this issue.
