### ISSUE TITLE
sims/* broken by recent changes to global vars

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/together#7]
The contents of the sims/ directory looks like it a collection of built sims.  These will no longer work with master due to changes to global variables in https://github.com/phetsims/tasks/issues/160.

Longterm, I'd advise against having prebuilt sims checked in like this.

**Comment by samreid** [comment]
> The contents of the sims/ directory looks like it a collection of built sims. These will no longer work with master due to changes to global variables in phetsims/tasks#160.

They are built, so I don't understand why they would need to work with master--they are completely isolated.  This directory is a place to serve static snapshots of sims for the gh-pages demos so that they are served from the same domain and don't have cross-domain problems.  I normally exclude these from my IDE paths.  Wasn't sure of the best place to document all that--should I put it in the README or something?

**Comment by pixelzoom** [comment]
I didn't know if they needed to work with master, just wanted to point out that they won't. I had no way of knowing how they are used, so assumed that they were for testing together. A README in sims/, containing the info above, is recommended.

**Comment by samreid** [comment]
I added docs above, you can see it in context here:
https://github.com/phetsims/together/tree/gh-pages/sims
